#!/usr/bin/env python3
# -------------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright The TrustedFirmware-M Contributors
#
# SPDX-License-Identifier: BSD-3-Clause
#
# -------------------------------------------------------------------------------

"""Generate the AES-KW image encryption keys embedded in BL2.

The key files hold "AES-KW:" followed by the base64 encoded key, the
format consumed by imgtool.
"""

import argparse
import base64
import sys

KEY_PREFIX = "AES-KW:"
KEY_SIZES = (16, 32)


def read_key(path):
    with open(path, "r", encoding="utf-8") as key_file:
        content = key_file.read().strip()
    if not content.startswith(KEY_PREFIX):
        sys.exit(f"{path}: key does not start with {KEY_PREFIX}")
    key = base64.b64decode(content[len(KEY_PREFIX):], validate=True)
    if len(key) not in KEY_SIZES:
        sys.exit(f"{path}: key must be 16 or 32 bytes, not {len(key)}")
    return key


def emit_array(out, name, key):
    out.write(f"const unsigned char {name}[{len(key)}] = {{\n")
    for offset in range(0, len(key), 8):
        chunk = ", ".join(f"0x{byte:02x}" for byte in key[offset:offset + 8])
        out.write(f"    {chunk},\n")
    out.write("};\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--key-s", required=True,
                        help="key file for the secure image")
    parser.add_argument("--key-ns", required=True,
                        help="key file for the non-secure image")
    parser.add_argument("-o", "--output", required=True,
                        help="generated C source file")
    args = parser.parse_args()

    key_s = read_key(args.key_s)
    key_ns = read_key(args.key_ns)
    if len(key_s) != len(key_ns):
        sys.exit("the secure and non-secure keys must have the same size")

    with open(args.output, "w", encoding="utf-8") as out:
        out.write("/* Autogenerated by generate_kw_keys.py, do not edit. */\n")
        emit_array(out, "enc_key_s", key_s)
        emit_array(out, "enc_key_ns", key_ns)
        out.write(f"const unsigned int enc_key_len = {len(key_s)};\n")


if __name__ == "__main__":
    main()
